profile home-single {
	output "Lenovo Group Limited 27Q-11 UR338VFX" mode 2560x1440@300Hz position 0,0 enable
}

profile home-single-with-bugs {
	output "Lenovo Group Limited 27Q-11 UR338VFX" mode 2560x1440@300Hz position 0,0 enable
    output Unknown-1 disable
}

profile laptop-dock-home {
	output "Lenovo Group Limited 27Q-11 UR338VFX" mode 1920x1080@120Hz position 0,0 enable
    output "eDP-1" disable
}

profile laptop-dock-work {
    output "Lenovo Group Limited T34w-30 V30CFDHX" mode 3440x1440 position 0,0
    output "eDP-1" disable
}

profile laptop-dock-work2 {
    output "Lenovo Group Limited T34w-30 V30CFDF8" mode 3440x1440 position 0,0
    output "eDP-1" disable
}

profile bibse {
    output "Lenovo Group Limited P24QD-40 *" mode 2560x1440@120Hz position 0,0 enable
    output "eDP-1" position 320,1440 enable
}

profile laptop-nodock {
    output "eDP-1" enable
}

profile laptop-random {
    output "eDP-1" disable
    output "AOC Q27G42ZE 2RMR4HA003947" mode 1920x1080@120Hz position 0,0 enable
}

profile laptop-tv {
    output "eDP-1" disable
    output "LG TV SSCR2" mode 3840x2160 position 0,0
}
