local M = {}

M.highlights_base = function (colors)
	return {
		Normal = { fg = colors.foreground, bg = colors.background },
		StatusLineNC = { bg = "NONE", fg = "NONE" }, --see https://github.com/neovim/neovim/issues/19803
		StatusLine = { bg = colors.contrast, fg = colors.foreground },
		SignColumn = { bg = "NONE" },
		MsgArea = { fg = colors.foreground, bg = colors.background },
		ModeMsg = { fg = colors.foreground, bg = colors.background },
		MsgSeparator = { fg = colors.foreground, bg = colors.background },
		SpellBad = { fg = colors.color2 },
		SpellCap = { fg = colors.color6 },
		SpellLocal = { fg = colors.color4 },
		SpellRare = { fg = colors.color6 },
		NormalNC = { fg = colors.foreground, bg = colors.background },
		Pmenu = { fg = colors.foreground, bg = colors.contrast },
		PmenuSel = { fg = "NONE", bg = colors.color8 },
		WildMenu = { fg = colors.color7, bg = colors.color4 },
		Folded = { fg = colors.color4, bg = colors.background },
		FoldColumn = { fg = colors.color4, bg = colors.background },
		LineNr = { fg = colors.contrast, bg = colors.background },
		FloatBorder = { fg = colors.contrast, bg = colors.contrast },
		Whitespace = { fg = colors.color1 },
		VertSplit = { bg = colors.background, fg = colors.color8 },
		CursorLine = { bg = "NONE" },
		CursorLineNr = { fg = colors.cursorline },
		CursorColumn = { bg = colors.background },
		ColorColumn = { bg = colors.background },
		NormalFloat = { bg = colors.contrast, fg = colors.foreground },
		Visual = { bg = colors.color8, fg = colors.foreground },
		VisualNOS = { bg = colors.background },
		WarningMsg = { fg = colors.color3, bg = colors.background },
		DiffAdd = { bg = colors.background, fg = colors.color4 },
		DiffChange = { bg = colors.background, fg = colors.color5 },
		DiffDelete = { bg = colors.background, fg = colors.color1 },
		QuickFixLine = { bg = colors.background },
		PmenuSbar = { bg = colors.contrast },
		PmenuThumb = { bg = colors.color2 },
		MatchParen = { fg = colors.color12, bg = colors.background },
		Cursor = { fg = colors.background, bg = colors.cursor },
		lCursor = { fg = colors.background, bg = colors.cursor },
		CursorIM = { fg = colors.background, bg = colors.cursor },
		TermCursor = { fg = colors.background, bg = colors.cursor },
		TermCursorNC = { fg = colors.background, bg = colors.cursor },
		Conceal = { fg = colors.color4, bg = colors.background },
		Directory = { fg = colors.color4 },
		SpecialKey = { fg = colors.color4 },
		ErrorMsg = { fg = colors.color1, bg = colors.background },
		Search = { fg = colors.background, bg = colors.color10 },
		IncSearch = { fg = colors.background, bg = colors.color10 },
		Substitute = { fg = colors.color3, bg = colors.color6 },
		MoreMsg = { fg = colors.color5 },
		Question = { fg = colors.color5 },
		EndOfBuffer = { fg = colors.background },
		NonText = { fg = colors.color1 },
        StorageClass = { fg = colors.color7 },

		Boolean = { fg = colors.color6 },
		Character = { fg = colors.color4 },
		Comment = { fg = colors.comment, italic = true },
		Constant = { fg = colors.color6 },
        Variable = { fg = colors.foreground },
		String = { fg = colors.color2 },
		Number = { fg = colors.color3 },
		Float = { fg = colors.color8 },
		Keyword = { fg = colors.color5, italic = true, bold = true },
		Identifier = { fg = colors.color1},
		Function = { fg = colors.color1 },
		Operator = { fg = colors.color12 },
		Type = { fg = colors.color3 },
		Label = { fg = colors.color4 },
		Delimiter = { fg = colors.color7 },
		Special = { fg = colors.color6 },
		Define = { fg = colors.color3 },
        SpecialChar = { fg = colors.color4 },
		Macro = { fg = colors.color2 },
		PreProc = { fg = colors.color4 },
		Include = { fg = colors.color9 },
		Conditional = { fg = colors.color1 },
		Repeat = { fg = colors.color11 },
		Exception = { fg = colors.color9},
		Title = { fg = colors.color4, bold = true },

        Structure = { fg = colors.color6 },
		Typedef = { fg = colors.color6 },
        Statement = { fg = colors.color6 },
		PreCondit = { fg = colors.color6 },
		Tag = { fg = colors.color4 },
		Debug = { fg = colors.color1 },
		SpecialComment = { fg = colors.comment },
		Ignore = { fg = colors.color7, bg = colors.background },
		Todo = { fg = colors.color1, bg = colors.background },
		Error = { fg = colors.color1, bg = colors.background },
		TabLine = { fg = colors.color2, bg = colors.background },
		TabLineSel = { fg = colors.foreground, bg = colors.background },
		TabLineFill = { fg = colors.foreground, bg = colors.background },

		-- treesitter up here cuz im linking default hls
		["@attribute"] = { link = "PreProc" },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@comment"] = { link = "Comment" },
		["@conditional"] = { link = "Conditional" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Special" },
		["@constant.macro"] = { link = "Define" },
		["@constructor"] = { link = "Special" },
		["@exception"] = { link = "Exception" },
		["@field"] = { link = "Identifier" },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Special" },
		["@function.macro"] = { link = "Macro" },
		["@include"] = { link = "Include" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Function" },
		["@keyword.operator"] = { link = "Operator" },
		["@keyword.return"] = { link = "Keyword" },
		["@label"] = { link = "Label" },
		["@method"] = { link = "Function" },
		["@namespace"] = { link = "Include" },
		["@number"] = { link = "Number" },
		["@parameter"] = { link = "Identifier" },
		["@parameter.reference"] = { link = "Identifier" },
		["@property"] = { link = "Identifier" },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.bracket"] = { link = "Delimiter" },
		["@punctuation.special"] = { link = "Delimiter"},
		["@repeat"] = { link = "Repeat" },
		["@string"] = { link = "String" },
		["@string.regex"] = { link = "String" },
		["@string.escape"] = { link = "SpecialChar" },
		["@string.special"] = { link = "SpecialChar" },
		["@symbol"] = { link = "Identifier" },
		["@tag"] = { fg = colors.color4 },
		["@tag.attribute"] = { fg = colors.color1 },
		["@tag.delimiter"] = { fg = colors.color7 },
		["@text"] = { fg = colors.foreground },
		["@text.strong"] = { fg = colors.color7, bold = true },
		["@text.emphasis"] = { italic = true, fg = colors.color7 },
		["@text.underline"] = { fg = colors.foreground, underline = true },
		["@text.strike"] = { fg = colors.color7, strikethrough = true },
		["@text.title"] = { link = "Title" },
		["@text.literal"] = { link = "String" },
		["@text.uri"] = { fg = colors.color4, underline = true },
		["@text.math"] = { link = "Special" },
		["@text.reference"] = { link = "Constant" },
		["@text.environment"] = { link = "Macro" },
		["@text.environment.name"] = { link = "Type" },
		["@text.note"] = { fg = colors.color8 },
		["@text.warning"] = { fg = colors.color11 },
		["@text.danger"] = { fg = colors.color9 },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "Type" },
		["@variable"] = { link = "Variable" },
		["@variable.builtin"] = { link = "Special" },

        StatusLineModeNormal = { fg = colors.contrast, bg = colors.color18 },
        StatusLineModeInsert = { fg = colors.contrast, bg = colors.color20 },
        StatusLineModeVisual = { fg = colors.contrast, bg = colors.color21 },
        StatusLineModeReplace = { fg = colors.contrast, bg = colors.color17 },
        StatusLineModeCmd = { fg = colors.contrast, bg = colors.color19 },
        StatusLineModeTerminal = { fg = colors.contrast, bg = colors.color17 },
        StatusLineFileName = { fg = colors.foreground, bg = colors.contrast },
        StatusLineFileModified = { fg = colors.comment, bg = colors.contrast },
        StatusLineTerminalSymbol = { fg = colors.foreground, bg = colors.color16 },
        StatusLineFileexplorerSymbol = { fg = colors.foreground, bg = colors.color20 },
        StatusLinePackagemanagerSymbol = { fg = colors.foreground, bg = colors.color19 },
		StatusLineDiagnosticError = { fg = colors.color9, bg = colors.contrast },
		StatusLineDiagnosticWarn = { fg = colors.color11, bg = colors.contrast },
		StatusLineDiagnosticInfo = { fg = colors.color12, bg = colors.contrast },
		StatusLineDiagnosticHint = { fg = colors.color10, bg = colors.contrast },

        BffmgrKey = { fg = colors.color1 },
        BffmgrBufname = { fg = colors.color4 },

        NotifyERRORBorder = { fg=colors.color1 },
        NotifyWARNBorder = { fg=colors.color3 },
        NotifyINFOBorder = { fg=colors.color2 },
        NotifyDEBUGBorder = { fg=colors.color7 },
        NotifyTRACEBorder = { fg=colors.color6 },
        NotifyERRORIcon = {link = "NotifyERRORBorder"},
        NotifyWARNIcon = {link = "NotifyWARNBorder"},
        NotifyINFOIcon = {link = "NotifyINFOBorder"},
        NotifyDEBUGIcon = {link = "NotifyDEBUGBorder"},
        NotifyTRACEIcon = {link = "NotifyTRACEBorder"},
        NotifyERRORTitle = {link = "NotifyERRORTitle"},
        NotifyWARNTitle = {link = "NotifyWARNTitle"},
        NotifyINFOTitle = {link = "NotifyINFOBorder"},
        NotifyDEBUGTitle = {link = "NotifyDEBUGBorder"},
        NotifyTRACETitle = {link = "NotifyTRACEBorder"},
        NotifyERRORBody = {link = "Normal"},
        NotifyWARNBody = {link = "Normal"},
        NotifyINFOBody = {link = "Normal"},
        NotifyDEBUGBody = {link = "Normal"},
        NotifyTRACEBody = {link = "Normal"},

		-- CMP
		CmpItemAbbr = { fg = colors.foreground, bg = "NONE" },
		CmpItemAbbrDeprecated = { fg = colors.color1, strikethrough = true, bg = "NONE" },
		CmpItemAbbrMatch = { fg = colors.color12, bg = "NONE", bold = true },
		CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch", bold = true },
		CmpItemKindKeyword = { fg = colors.foreground, bg = colors.color22 },
		CmpItemKindVariable = { fg = colors.foreground, bg = colors.color19 },
		CmpItemKindFunction = { fg = colors.foreground, bg = colors.color20 },
		CmpItemKindMethod = { link = "CmpItemKindFunction" },
		CmpItemKindText = { link = "CmpItemKindKeyword" },
		CmpItemKindEnum = { fg = colors.foreground, bg = colors.color20 },
		CmpItemKindProperty = { fg = colors.foreground, bg = colors.color18 },
		CmpItemKindConstructor = { fg = colors.foreground, bg = colors.color21 },
		CmpItemKindField = { fg = colors.foreground, bg = colors.color16 },
		CmpItemKindClass = { link = "CmpItemKindEnum" },
		CmpItemKindInterface = { fg = colors.foreground, bg = colors.color20 },
		CmpItemKindModule = { fg = colors.foreground, bg = colors.color23 },
		CmpItemKindSnippet = { fg = colors.foreground, bg = colors.color17 },
		CmpItemKindStruct = { link = "CmpItemKindConstructor" },
		CmpItemKindConst = { link = "CmpItemKindProperty" },
        CmpItemKindEvent = { fg = colors.foreground, bg = colors.color19 },
		CmpItemMenu = { fg = colors.color5, italic=true, bg = "NONE" },
       
        -- Aerial HL maps to Treesitter
        -- AerialKeyIcon = { link = "Keyword" },

		-- Builtin LSP highlights
		LspReferenceText = { fg = colors.background, bg = colors.color12 },
		LspReferenceRead = { fg = colors.background, bg = colors.color12 },
		LspReferenceWrite = { fg = colors.background, bg = colors.color12 },

		-- Diagnostic
		DiagnosticError = { fg = colors.color9, bg = "NONE" },
		DiagnosticWarn = { fg = colors.color11, bg = "NONE" },
		DiagnosticInfo = { fg = colors.color12, bg = "NONE" },
		DiagnosticHint = { fg = colors.color10, bg = "NONE" },

		-- LspTrouble
		LspTroubleText = { fg = colors.foreground },
		LspTroubleCount = { fg = colors.color6, bg = colors.foreground },
		LspTroubleNormal = { fg = colors.foreground, bg = colors.background },

		-- Illuminate
		illuminatedWord = { bg = colors.foreground },
		illuminatedCurWord = { bg = colors.foreground },

		-- diff
		diffAdded = { fg = colors.color4 },
		diffRemoved = { fg = colors.color1 },
		diffChanged = { fg = colors.color5 },
		diffOldFile = { fg = colors.color5 },
		diffNewFile = { fg = colors.color5 },
		diffFile = { fg = colors.color7 },
		diffLine = { fg = colors.color1 },
		diffIndexLine = { fg = colors.color6 },

		-- Neogit
		NeogitBranch = { fg = colors.color6 },
		NeogitRemote = { fg = colors.color6 },
		NeogitHunkHeader = { bg = colors.background, fg = colors.foreground },
		NeogitHunkHeaderHighlight = { bg = colors.comment, fg = colors.color7 },
		NeogitDiffContextHighlight = { bg = colors.background, fg = colors.foreground },
		NeogitDiffDeleteHighlight = { fg = colors.color1, bg = colors.background },
		NeogitDiffAddHighlight = { fg = colors.color4, bg = colors.background },

		-- GitGutter
		-- GitGutterAdd = { fg = colors.color10 }, -- diff mode: Added line |diff.txt|
		-- GitGutterChange = { fg = colors.color13 }, -- diff mode: Changed line |diff.txt|
		-- GitGutterDelete = { fg = colors.color9 }, -- diff mode: Deleted line |diff.txt|
		GitGutterAdd = { fg = colors.color17 }, -- diff mode: Added line |diff.txt|
		GitGutterChange = { fg = colors.color20 }, -- diff mode: Changed line |diff.txt|
		GitGutterDelete = { fg = colors.color16 }, -- diff mode: Deleted line |diff.txt|

		-- GitSigns
		GitSignsAdd = { link = "GitGutterAdd" }, -- diff mode: Added line |diff.txt|
		GitSignsChange = { link = "GitGutterChange" }, -- diff mode: Changed line |diff.txt|
		GitSignsDelete = { link = "GitGutterDelete" }, -- diff mode: Deleted line |diff.txt|

		-- Telescope
		TelescopeNormal = { bg = colors.background_dark },
		TelescopeBorder = { bg = colors.background_dark, fg = colors.background_dark },
		TelescopePromptBorder = { bg = colors.background_dark, fg = colors.background_dark },
		TelescopePromptTitle = { bg = colors.color16, fg = colors.foreground },
		TelescopePreviewNormal = { bg = colors.contrast, fg = colors.foreground },
		TelescopePreviewBorder = { bg = colors.contrast, fg = colors.contrast },
		TelescopePreviewTitle = { bg = colors.color17, fg = colors.foreground },
        TelescopePreviewMatch = { bg = colors.contrast },
        TelescopePreviewLine = { bg = colors.background_dark },
		TelescopeSelection = { bg = colors.contrast },
		-- Indent Blank Line
		IndentBlanklineChar = { fg = colors.color8, bg = colors.background },

		--gleipnir Dashboard highlights
		DashboardHeader = { fg = colors.color7 },
        DashboardIcon = { fg = colors.color4 },
        DashboardKey = { fg = colors.color5 },
        DashboardDesc = { fg = colors.color15 },
		DashboardCenter = { fg = colors.color4 },
		DashboardShortCut = { fg = colors.color2 },
		DashboardFooter = { fg = colors.comment },

		-- NvimTree
		NvimTreeNormal = { fg = colors.foreground, bg = colors.background },
		NvimTreeNormalNC = { fg = colors.foreground, bg = colors.background },
		NvimTreeRootFolder = { fg = colors.color1 },
		NvimTreeGitDirty = { fg = colors.color5 },
		NvimTreeGitNew = { fg = colors.color4 },
		NvimTreeGitDeleted = { fg = colors.color1 },
		NvimTreeSpecialFile = { fg = colors.color6 },
		NvimTreeIndentMarker = { fg = colors.color8 },
		NvimTreeImageFile = { fg = colors.foreground },
		NvimTreeSymlink = { fg = colors.color7 },
		NvimTreeFolderIcon = { fg = colors.color4, bg = colors.background },
		NvimTreeFolderName = { fg = colors.foreground },
		NvimTreeOpenedFolderName = { fg = colors.color4 },
		NvimTreeEmptyFolderName = { fg = colors.color2 },
		NvimTreeStatusLineNC = { bg = colors.background, fg = colors.background },

		-- LspSaga
		LspFloatWinNormal = { bg = colors.background },
		LspFloatWinBorder = { fg = colors.background },
		LspSagaBorderTitle = { fg = colors.color7 },
		LspSagaHoverBorder = { fg = colors.color7 },
		LspSagaRenameBorder = { fg = colors.color4 },
		LspSagaDefPreviewBorder = { fg = colors.color4 },
		LspSagaCodeActionBorder = { fg = colors.color7 },
		LspSagaFinderSelection = { fg = colors.color1 },
		LspSagaCodeActionTitle = { fg = colors.color7 },
		LspSagaCodeActionContent = { fg = colors.color6 },
		LspSagaSignatureHelpBorder = { fg = colors.color1 },

		LspSagaWinbarSep = { fg = colors.color8, bg = colors.contrast },
		LspSagaWinbarEnum = { fg = colors.color5, bg = colors.contrast },

        DapBreakpointSymbol = { fg = colors.color1 },

		ReferencesCount = { fg = colors.color6 },
		DefinitionCount = { fg = colors.color6 },
		DefinitionIcon = { fg = colors.color7 },
		ReferencesIcon = { fg = colors.color7 },
		TargetWord = { fg = colors.color7 },

		-- NeoVim
		healthError = { fg = colors.color1 },
		healthSuccess = { fg = colors.color4 },
		healthWarning = { fg = colors.color5 },

		-- BufferLine
		BufferLineIndicatorSelected = { fg = colors.color2 },
		BufferLineFill = { fg = colors.background, bg = colors.background },

		-- BarBar Bufferline
		BufferCurrent = { fg = colors.foreground, bg = colors.background, bold = true },
		BufferCurrentMod = { fg = colors.color12, bg = colors.background, bold = true },
		BufferCurrentSign = { fg = colors.background, bg = colors.background },
		BufferVisible = { fg = colors.foreground, bg = colors.background, bold = true },
		BufferVisibleMod = { fg = colors.color4, bg = colors.background, bold = true },
		BufferVisibleSign = { fg = colors.background, bg = colors.background },
		BufferInactive = { fg = colors.color15, bg = colors.inactive_tabs },
		BufferInactiveMod = { fg = colors.color15, bg = colors.inactive_tabs, bold = true },
		BufferInactiveSign = { fg = colors.background_dark, bg = colors.inactive_tabs },
		BufferTabpageFill = { fg = colors.background_dark, bg = colors.background_dark },
		BufferOffset = { fg = colors.background, bg = colors.background }
	}
end

return M
